### ISSUE TITLE
Change  mask size

### ISSUE THREAD

**Issue by napoAI** [instant-high/wav2lip-onnx-256#4]
Hello, 

How can I Change  mask size, feathering and mouth_tracking?

This is the code I use: 
python -W ignore inference_onnxModel.py --checkpoint_path "checkpoints\wav2lip_256.onnx" --face "C:\Users\napo_\Downloads\wav2lip-onnx-256-main\face\0.mp4" --audio "C:\Users\napo_\Downloads\wav2lip-onnx-256-main\audio\3.wav" --outfile "C:\Users\napo_\Downloads\wav2lip-onnx-256-main\audio\3" --nosmooth --pads 0 10 0 0 --fps 29.97

**Comment by napoAI** [comment]
??

**Comment by instant-high** [comment]
This is the minimum version.
I only replaced original face detection with insightface function.
So no alignment, only bboxes.
You can only use --pads parameter same way as in original wav2lip.

**Comment by napoAI** [comment]
Hello, 

I use this version: Easy_Wav2Lip_v8.3.ipynb -  which is quite good because it is relatively easy to use but it still has faults especially when the face is very close you can see that the lips are not real

I would be happy if you could recommend another version that might be better and easier to work with

**Comment by instant-high** [comment]
You can try this.
https://github.com/instant-high/wav2lip-onnx-HQ
I updated the script so it should work with wav2lip_256.onnx in checkpoints folder.
Use --checkpoint then

But it is also cli version. 
But with face alignment , enhancer ....

**Comment by napoAI** [comment]
Please explain to me how to activate it, I didn't understand

**Comment by instant-high** [comment]
@napoAI 
 Someone made this:
https://youtu.be/OW9hhyS7bWQ?si=Elew5z7XoS8WoDv6

**Comment by napoAI** [comment]
Yes, I know it, it's a little more difficult to activate it, I got stuck in the middle, you told me that I need to install ffmpeg, but I still can't get it working

**Comment by instant-high** [comment]
If you're on windows it should also work if you put ffmpeg.exe into root directory of wav2lip.
